### ISSUE TITLE
Import in android Studio available?

### ISSUE THREAD

**Issue by MayeuldP** [davidmi/Android-TMX-Loader#5]
Hello, 
I was wondering, I got a .tmx map, and I wanted to know if it was possible to use Android-TMX-loader inside "Android Studio" to read it ? 
If yes, do you have a setup guide to do it ? 

Thank's for your help.

**Comment by davidmi** [comment]
I haven't updated this project in a while, so there's no Android Studio support currently. However, if you would find it useful, I can update the project for Android Studio.
